name: Deploying changes to EC2 via Jumpbox (OIDC + Instance Connect)

'on':
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout (for workflow files only, not deployment)
      - name: Checkout code
        uses: actions/checkout@v4

      # AWS OIDC authentication
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN  }}
          aws-region: ${{ secrets.AWS_REGION }}

      # GitHub App token (org-wide, secure, short-lived)
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      # Generate temporary SSH key
      - name: Generate ephemeral SSH key
        run: |
          ssh-keygen -t ed25519 -f /tmp/gh_key -N ""
          chmod 600 /tmp/gh_key

      # Push temporary key to jumpbox
      - name: Inject SSH key into Jumpbox
        run: |
          aws ec2-instance-connect send-ssh-public-key \
            --instance-id ${{ secrets.JUMPBOX_INSTANCE_ID  }} \
            --availability-zone ${{ secrets.JUMPBOX_AZ  }} \
            --instance-os-user ubuntu \
            --ssh-public-key file:///tmp/gh_key.pub

      # Deploy via Jumpbox → Private EC2 (nested SSH)
      - name: Deploy via jumpbox (nested SSH)
        run: |
          ssh \
            -i /tmp/gh_key \
            -o StrictHostKeyChecking=no \
            ubuntu@${{ secrets.JUMPBOX_HOST }} << 'JUMPBOX'

          echo "Connected to jumpbox: $(whoami)@$(hostname)"

          ssh \
            -i ~/bastion-server.pem \
            -o StrictHostKeyChecking=no \
            ubuntu@${{ secrets.TARGET_HOST }} << 'PRIVATE'

          set -euo pipefail
          echo "Connected to private EC2: $(whoami)@$(hostname)"
          echo "Deploy started at: $(date)"

          # Load Node environment
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

          # Env variable setup
          export GITHUB_TOKEN="${{ steps.app-token.outputs.token }}"
          export REPO_NAME="${{ github.event.repository.name }}"

          cd /home/ubuntu/$REPO_NAME

          git checkout main
          git -c credential.helper='!f() { echo username=x-access-token; echo password=$GITHUB_TOKEN; }; f' pull

          npm i
          npm run build

          pm2 reload $REPO_NAME

          PRIVATE
          JUMPBOX
